# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  schedule:
    - cron:  '* 0 * * *'
  push:
    branches:
      - '**'


env:
  GH_TOKEN: ${{ secrets.GH_TOKEN }}

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  Linux:
    runs-on: ubuntu-20.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: "3.8"

      - name: Install system requirements
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          sudo apt-get update && sudo apt-get -qq install -y --no-install-recommends pkg-config g++ make

      - name: install conan
        run: pip3 install conan --ignore-installed

      - name: install hooks
        run: |
          conan config install hooks -tf hooks
          conan config set hooks.conan-center
      - name: run
        shell: bash
        env:
          CONAN_SYSREQUIRES_MODE: disabled
          CONAN_HOOK_ERROR_LEVEL: 40
        run: |
          pip3 install pyyaml requests aiohttp
          python3 main.py
